[package]
name = "is_i32"
version = "0.1.0"
edition = "2021"
description = "A blazingly fast algorithm to compute whether or not a value is an i32"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
